version: '3'

services:
  postlocation:
    build: ./service1/
    container_name: service_location
    command: python3 service1.py ${SERVER_URL?} ${BIKE_ID}
    restart: on-failure
    network_mode: host
  listenwebsocket:
    build: ./service2/
    container_name: service_keylock
    command: python3 service2.py ${SERVER_URL?} ${BIKE_ID}
    restart: on-failure
    network_mode: host
#docker-compose --env-file ./config/.env up